/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attachment: typeof import('./src/components/base/fields/Attachment.vue')['default']
    Boolean: typeof import('./src/components/base/fields/Boolean.vue')['default']
    Character: typeof import('./src/components/base/fields/Character.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Facet: typeof import('./src/components/base/view_items/Facet.vue')['default']
    FormView: typeof import('./src/components/views/FormView.vue')['default']
    GroupWidget: typeof import('./src/components/base/widgets/GroupWidget.vue')['default']
    HeaderButtonView: typeof import('./src/components/views/HeaderButtonView.vue')['default']
    HeaderWidget: typeof import('./src/components/base/widgets/HeaderWidget.vue')['default']
    Image: typeof import('./src/components/base/fields/Image.vue')['default']
    ListView: typeof import('./src/components/views/ListView.vue')['default']
    Many2one: typeof import('./src/components/base/fields/Many2one.vue')['default']
    MenuView: typeof import('./src/components/views/MenuView.vue')['default']
    NotebookWidget: typeof import('./src/components/base/widgets/NotebookWidget.vue')['default']
    Number: typeof import('./src/components/base/fields/Number.vue')['default']
    PageHeader: typeof import('./src/components/views/PageHeader.vue')['default']
    PageWidget: typeof import('./src/components/base/widgets/PageWidget.vue')['default']
    RecordView: typeof import('./src/components/RecordView.vue')['default']
    RenderField: typeof import('./src/components/base/RenderField.vue')['default']
    RootMenuView: typeof import('./src/components/views/RootMenuView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchView: typeof import('./src/components/views/SearchView.vue')['default']
    Selection: typeof import('./src/components/base/fields/Selection.vue')['default']
    SheetWidget: typeof import('./src/components/base/widgets/SheetWidget.vue')['default']
    TableView: typeof import('./src/components/views/TableView.vue')['default']
    ToMany: typeof import('./src/components/base/fields/ToMany.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
